#!/usr/bin/env bash
# SentinelX Docker — install.sh
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/pensados/sentinelx-docker/main/install.sh | bash
#
# What it does:
#   1. Checks prerequisites (docker, docker compose, git)
#   2. Clones sentinelx-docker with submodules
#   3. Generates .env with a random SENTINEL_TOKEN
#   4. Prompts for OIDC config
#   5. Builds and starts the stack

set -euo pipefail

REPO_URL="https://github.com/pensados/sentinelx-docker"
INSTALL_DIR="${SENTINELX_DIR:-$HOME/sentinelx-docker}"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
NC="\033[0m"

info()    { echo -e "${GREEN}[sentinelx]${NC} $*"; }
warn()    { echo -e "${YELLOW}[sentinelx]${NC} $*"; }
error()   { echo -e "${RED}[sentinelx] ERROR:${NC} $*" >&2; exit 1; }

echo ""
echo "  ███████╗███████╗███╗   ██╗████████╗██╗███╗   ██╗███████╗██╗     ██╗  ██╗"
echo "  ██╔════╝██╔════╝████╗  ██║╚══██╔══╝██║████╗  ██║██╔════╝██║     ╚██╗██╔╝"
echo "  ███████╗█████╗  ██╔██╗ ██║   ██║   ██║██╔██╗ ██║█████╗  ██║      ╚███╔╝ "
echo "  ╚════██║██╔══╝  ██║╚██╗██║   ██║   ██║██║╚██╗██║██╔══╝  ██║      ██╔██╗ "
echo "  ███████║███████╗██║ ╚████║   ██║   ██║██║ ╚████║███████╗███████╗██╔╝ ██╗"
echo "  ╚══════╝╚══════╝╚═╝  ╚═══╝   ╚═╝   ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝╚═╝  ╚═╝"
echo "  Docker installer"
echo ""

# ── 1. Prerequisites ─────────────────────────────────────────────────────────

info "Checking prerequisites..."

command -v git    >/dev/null 2>&1 || error "git is required. Install it with: apt install git"
command -v docker >/dev/null 2>&1 || error "Docker is required. See: https://docs.docker.com/engine/install"

if ! docker compose version >/dev/null 2>&1; then
    error "Docker Compose v2 is required. See: https://docs.docker.com/compose/install"
fi

if ! docker info >/dev/null 2>&1; then
    error "Docker daemon is not running or current user cannot access it.\nTry: sudo usermod -aG docker \$USER && newgrp docker"
fi

DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null)
COMPOSE_VERSION=$(docker compose version --short 2>/dev/null)
info "Docker $DOCKER_VERSION / Compose $COMPOSE_VERSION — OK"

# ── 2. Clone ─────────────────────────────────────────────────────────────────

if [ -d "$INSTALL_DIR/.git" ]; then
    info "Directory $INSTALL_DIR already exists — pulling latest..."
    git -C "$INSTALL_DIR" pull --recurse-submodules
    git -C "$INSTALL_DIR" submodule update --init --recursive
else
    info "Cloning sentinelx-docker into $INSTALL_DIR ..."
    git clone --recurse-submodules "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# ── 3. Generate .env ─────────────────────────────────────────────────────────

if [ -f .env ]; then
    warn ".env already exists — skipping generation. Edit it manually if needed."
else
    info "Generating .env ..."
    SENTINEL_TOKEN=$(openssl rand -hex 32)

    cat > .env <<EOF
# SentinelX Docker — generated by install.sh
# Keep this file secret — do not commit it.

SENTINEL_TOKEN=${SENTINEL_TOKEN}

# Execution mode: host (default) or container
# host      → commands run on the HOST via nsenter (requires pid=host + privileged=true)
# container → commands run inside the container only (isolated, no special privileges)
SENTINEL_EXEC_MODE=host

# OIDC — fill in your provider values
OIDC_ISSUER=
OIDC_JWKS_URI=
OIDC_EXPECTED_AUDIENCE=
RESOURCE_URL=https://sentinelx.example.com
AUTH_DEBUG=false
EOF
    chmod 600 .env
    info "Generated .env with random SENTINEL_TOKEN."
fi

# ── 4. Install pensa-safe-edit on the host ───────────────────────────────────
# sentinelx-core includes the pensa-safe-edit binary in bin/.
# In host mode (SENTINEL_EXEC_MODE=host), the agent calls it via nsenter
# using the host's PATH — so it needs to be installed on the host.

info "Installing pensa-safe-edit on the host..."
SAFE_EDIT_SRC="$INSTALL_DIR/sentinelx-core/bin/sentinelx-safe-edit"
SAFE_EDIT_DST="/usr/local/bin/pensa-safe-edit"

if [ ! -f "$SAFE_EDIT_SRC" ]; then
    warn "pensa-safe-edit not found at $SAFE_EDIT_SRC — skipping."
    warn "Run: sudo cp sentinelx-core/bin/sentinelx-safe-edit /usr/local/bin/pensa-safe-edit"
else
    if sudo cp "$SAFE_EDIT_SRC" "$SAFE_EDIT_DST" && sudo chmod +x "$SAFE_EDIT_DST"; then
        info "pensa-safe-edit installed at $SAFE_EDIT_DST"
    else
        warn "Could not install pensa-safe-edit (needs sudo). Run manually:"
        warn "  sudo cp $SAFE_EDIT_SRC $SAFE_EDIT_DST && sudo chmod +x $SAFE_EDIT_DST"
    fi
fi

# ── 5. OIDC prompt ───────────────────────────────────────────────────────────

source .env 2>/dev/null || true

if [ -z "${OIDC_ISSUER:-}" ]; then
    echo ""
    warn "OIDC is not configured yet."
    warn "SentinelX MCP requires an OIDC provider (Keycloak, Auth0, etc.) to validate Claude's tokens."
    echo ""
    read -rp "  OIDC_ISSUER   (e.g. https://auth.example.com/realms/sentinelx): " INPUT_ISSUER
    read -rp "  OIDC_JWKS_URI (e.g. https://auth.example.com/realms/sentinelx/protocol/openid-connect/certs): " INPUT_JWKS

    if [ -n "$INPUT_ISSUER" ] && [ -n "$INPUT_JWKS" ]; then
        sed -i "s|^OIDC_ISSUER=.*|OIDC_ISSUER=${INPUT_ISSUER}|" .env
        sed -i "s|^OIDC_JWKS_URI=.*|OIDC_JWKS_URI=${INPUT_JWKS}|" .env
        info "OIDC configured."
    else
        warn "Skipping OIDC setup. Edit .env before using the MCP server."
    fi
fi

# ── 6. Build and start ───────────────────────────────────────────────────────

echo ""
info "Building and starting SentinelX..."
docker compose up -d --build

echo ""
info "Waiting for health checks..."
sleep 5

if docker compose ps | grep -q "healthy\|running"; then
    echo ""
    echo -e "${GREEN}✓ SentinelX is running!${NC}"
    echo ""
    docker compose ps
    echo ""
    info "Core agent:  http://127.0.0.1:8091"
    info "MCP server:  http://127.0.0.1:8099"
    echo ""
    info "Test the agent:"
    echo "  source $INSTALL_DIR/.env"
    echo "  curl -s -H \"Authorization: Bearer \$SENTINEL_TOKEN\" http://127.0.0.1:8091/capabilities | jq .mode"
    echo ""
    info "Logs: cd $INSTALL_DIR && docker compose logs -f"
else
    warn "Containers may still be starting. Check status with:"
    echo "  cd $INSTALL_DIR && docker compose ps"
    echo "  cd $INSTALL_DIR && docker compose logs"
fi
